"""
Visualize Shortest Path - Standalone Script
This script loads maze data from 'maze_data.json' (generated by maze_explorer.py),
randomly selects new start and target positions, and computes the shortest path
using only the barriers that were sensed by the robot during exploration.
"""

import json
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.animation import FuncAnimation
from collections import deque
import random

# Load maze data from JSON file
try:
    with open('maze_data.json', 'r') as f:
        data = json.load(f)
    print("\n✓ Maze data loaded from 'maze_data.json'")
except FileNotFoundError:
    print("\n" + "="*70)
    print("ERROR: maze_data.json not found!")
    print("="*70)
    print("Please run 'maze_explorer.py' first to generate the maze data.")
    print("="*70 + "\n")
    exit()

# Extract maze data
maze_map = data['maze_map']
sensed_barriers = data['sensed_barriers']
original_start = (data['start_position']['row'], data['start_position']['col'])
original_target = (data['target_position']['row'], data['target_position']['col'])

print("\n" + "="*70)
print("LOADED MAZE DATA FROM EXPLORATION")
print("="*70)
print(f"Maze Size: {maze_map['size']}x{maze_map['size']}")
print(f"Original Start (from exploration): {original_start}")
print(f"Original Target (from exploration): {original_target}")
print(f"Sensed Barriers: {len(sensed_barriers)} barriers")
print("="*70 + "\n")

# Randomly select NEW start and target positions
all_cells = [(r, c) for r in range(maze_map['size']) for c in range(maze_map['size'])]
start_position = random.choice(all_cells)
all_cells.remove(start_position)
target_position = random.choice(all_cells)

print("="*70)
print("RANDOMLY SELECTED NEW POSITIONS")
print("="*70)
print(f"New Start Position: {start_position}")
print(f"New Target Position: {target_position}")
print("="*70 + "\n")


def can_move(pos, direction, sensed_barriers, size):
    """Check if can move in direction based on SENSED barriers only"""
    r, c = pos
    
    # Check boundaries
    if direction == 'up' and r == 0: return False
    if direction == 'down' and r == size - 1: return False
    if direction == 'left' and c == 0: return False
    if direction == 'right' and c == size - 1: return False
    
    # Check sensed barriers
    barrier_check = {
        'up': ('h', r, c),
        'down': ('h', r + 1, c),
        'left': ('v', r, c),
        'right': ('v', r, c + 1)
    }
    
    # Convert sensed_barriers list to set of tuples for faster lookup
    barrier_set = set()
    for barrier in sensed_barriers:
        barrier_set.add((barrier['type'], barrier['row'], barrier['col']))
    
    # If barrier is sensed, cannot move
    if barrier_check[direction] in barrier_set:
        return False
    
    return True


def find_shortest_path(start, target, sensed_barriers, size):
    """Find shortest path using BFS based on SENSED barriers only"""
    if start == target:
        return [start]
    
    queue = deque([start])
    parent = {start: None}
    
    while queue:
        current = queue.popleft()
        if current == target:
            break
        
        for direction in ['up', 'down', 'left', 'right']:
            if can_move(current, direction, sensed_barriers, size):
                r, c = current
                next_pos = {
                    'up': (r-1, c), 'down': (r+1, c),
                    'left': (r, c-1), 'right': (r, c+1)
                }[direction]
                if next_pos not in parent:
                    parent[next_pos] = current
                    queue.append(next_pos)
    
    # Check if path was found
    if target not in parent:
        print("WARNING: No path found from start to target!")
        return [start]
    
    # Reconstruct path
    path = []
    current = target
    while current:
        path.append(current)
        current = parent.get(current)
    path.reverse()
    return path


# Compute shortest path using sensed barriers
print("🔍 Computing shortest path using sensed maze map...")
raw_path = find_shortest_path(start_position, target_position, sensed_barriers, maze_map['size'])

# Build detailed shortest path data
shortest_path = []
for i, (row, col) in enumerate(raw_path):
    cell_info = {
        'step': i,
        'row': row,
        'col': col,
        'x_cm': col * 30 + 15,
        'y_cm': row * 30 + 15,
    }
    
    if i > 0:
        prev_row, prev_col = raw_path[i-1]
        if row < prev_row: cell_info['direction'] = 'up'
        elif row > prev_row: cell_info['direction'] = 'down'
        elif col < prev_col: cell_info['direction'] = 'left'
        else: cell_info['direction'] = 'right'
    else:
        cell_info['direction'] = 'start'
    
    shortest_path.append(cell_info)

print(f"✓ Shortest path computed: {len(shortest_path)} steps\n")
print("="*70)
print("SHORTEST PATH ROUTE")
print("="*70)
for cell in shortest_path:
    print(f"  Step {cell['step']}: ({cell['row']}, {cell['col']}) -> {cell['direction']}")
print("="*70 + "\n")


# Create animation
fig, ax = plt.subplots(figsize=(10, 10))

def animate_path(frame):
    """Draw each frame of shortest path animation"""
    ax.clear()
    ax.set_xlim(-10, 160)
    ax.set_ylim(-30, 160)
    ax.invert_yaxis()
    ax.set_aspect('equal')
    
    # Draw cells
    for r in range(5):
        for c in range(5):
            rect = patches.Rectangle((c*30, r*30), 30, 30,
                                    linewidth=0.8, edgecolor='lightgray', 
                                    facecolor='white')
            ax.add_patch(rect)
    
    # Draw ONLY sensed barriers (from robot's exploration)
    for barrier in sensed_barriers:
        wall_type = barrier['type']
        r = barrier['row']
        c = barrier['col']
        if wall_type == 'h':
            ax.plot([c*30, (c+1)*30], [r*30, r*30], color='blue', linewidth=4, alpha=0.7)
        else:
            ax.plot([c*30, c*30], [r*30, (r+1)*30], color='blue', linewidth=4, alpha=0.7)
    
    # Draw complete path as dotted line
    if len(shortest_path) > 1:
        path_x = [cell['x_cm'] for cell in shortest_path]
        path_y = [cell['y_cm'] for cell in shortest_path]
        ax.plot(path_x, path_y, color='lime', linewidth=3, 
               linestyle='--', alpha=0.4)
    
    if frame < len(shortest_path):
        current_cell = shortest_path[frame]
        current_row = current_cell['row']
        current_col = current_cell['col']
        
        # Draw start
        sr, sc = start_position
        start_rect = patches.Rectangle((sc*30, sr*30), 30, 30,
                                      facecolor='lightgreen', alpha=0.6)
        ax.add_patch(start_rect)
        ax.text(sc*30+15, sr*30+15, 'START', ha='center', va='center',
               fontsize=10, weight='bold', color='darkgreen')
        
        # Draw target
        tr, tc = target_position
        target_rect = patches.Rectangle((tc*30, tr*30), 30, 30,
                                       facecolor='lightcoral', alpha=0.6)
        ax.add_patch(target_rect)
        ax.text(tc*30+15, tr*30+15, 'TARGET', ha='center', va='center',
               fontsize=10, weight='bold', color='darkred')
        
        # Draw traveled path
        for i in range(frame):
            cell = shortest_path[i]
            r, c = cell['row'], cell['col']
            if (r, c) != start_position and (r, c) != target_position:
                circle = patches.Circle((c*30+15, r*30+15), 6,
                                       facecolor='lime', edgecolor='darkgreen', 
                                       linewidth=2)
                ax.add_patch(circle)
        
        # Draw robot
        robot_circle = patches.Circle((current_col*30+15, current_row*30+15), 13,
                                     facecolor='orange', edgecolor='darkorange', 
                                     linewidth=3, zorder=10)
        ax.add_patch(robot_circle)
        ax.text(current_col*30+15, current_row*30+15, 'R', 
               ha='center', va='center', fontsize=16, 
               weight='bold', color='white', zorder=11)
        
        # Draw direction arrow
        if current_cell['direction'] != 'start':
            arrow_len = 12
            direction_map = {
                'up': (0, -arrow_len), 'down': (0, arrow_len),
                'left': (-arrow_len, 0), 'right': (arrow_len, 0)
            }
            if current_cell['direction'] in direction_map:
                dx, dy = direction_map[current_cell['direction']]
                ax.arrow(current_col*30+15, current_row*30+15, dx, dy,
                        head_width=6, head_length=5, 
                        fc='red', ec='red', linewidth=2, alpha=0.8, zorder=9)
        
        # Title
        steps_remaining = len(shortest_path) - 1 - current_cell['step']
        progress = (current_cell['step'] / (len(shortest_path) - 1) * 100) if len(shortest_path) > 1 else 100
        
        title = f"SHORTEST PATH (Using Sensed Maze) - Step {current_cell['step'] + 1}/{len(shortest_path)}\n"
        title += f"Position: ({current_row}, {current_col}) | "
        title += f"Direction: {current_cell['direction'].upper()} | "
        title += f"Progress: {progress:.0f}% | "
        title += f"Steps Remaining: {steps_remaining}"
        ax.set_title(title, fontsize=12, weight='bold', pad=15)
        
        # Legend
        legend_elements = [
            plt.Line2D([0], [0], marker='o', color='w', 
                      markerfacecolor='orange', markersize=12, 
                      label='Robot', markeredgecolor='darkorange', markeredgewidth=2),
            plt.Line2D([0], [0], marker='o', color='w', 
                      markerfacecolor='lime', markersize=10, 
                      label='Path Traveled', markeredgecolor='darkgreen'),
            plt.Line2D([0], [0], color='lime', linewidth=3, 
                      linestyle='--', label='Shortest Route'),
            plt.Line2D([0], [0], color='blue', linewidth=4, 
                      label='Sensed Barriers')
        ]
        ax.legend(handles=legend_elements, loc='upper left', 
                 bbox_to_anchor=(0, -0.05), ncol=2, frameon=True,
                 fontsize=9, fancybox=True, shadow=True)
        
        # Completion message
        if frame == len(shortest_path) - 1:
            ax.text(75, -20, '🎯 TARGET REACHED! 🎯\nOptimal Path Complete', 
                   ha='center', fontsize=14, weight='bold', color='green',
                   bbox=dict(boxstyle='round,pad=0.8', 
                            facecolor='yellow', edgecolor='green', 
                            linewidth=3, alpha=0.9))
    
    ax.set_xlabel('Distance (cm)', fontsize=11, weight='bold')
    ax.set_ylabel('Distance (cm)', fontsize=11, weight='bold')
    ax.grid(False)

print("Starting animation...")
anim = FuncAnimation(fig, animate_path, 
                    frames=len(shortest_path),
                    interval=500,
                    repeat=True, 
                    repeat_delay=2000)

plt.tight_layout()
plt.show()

print("\n✓ Animation complete!")
print(f"Robot navigated from {start_position} to {target_position}")
print(f"Total steps: {len(shortest_path)}")
print(f"Total distance: {(len(shortest_path) - 1) * 30} cm\n")